Repository k2-fsa/sherpa, pull requests merged in 2022-10, with the labels that each got.

#146 Streaming asr time stamp
  sherpa/bin/conv_emformer_transducer_stateless2/beam_search.py
  sherpa/bin/conv_emformer_transducer_stateless2/stream.py
  sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
  sherpa/bin/lstm_transducer_stateless/beam_search.py
  sherpa/bin/lstm_transducer_stateless/stream.py
  sherpa/bin/lstm_transducer_stateless/streaming_server.py
  sherpa/bin/pruned_stateless_emformer_rnnt2/beam_search.py
  sherpa/bin/pruned_stateless_emformer_rnnt2/stream.py
  sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_client.py
  sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
  sherpa/bin/streaming_pruned_transducer_statelessX/beam_search.py
  sherpa/bin/streaming_pruned_transducer_statelessX/stream.py
  sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
  sherpa/csrc/hypothesis.h
  sherpa/csrc/online_asr.cc
  sherpa/csrc/rnnt_beam_search.cc
  sherpa/csrc/rnnt_beam_search.h
  sherpa/python/csrc/hypothesis.cc
  sherpa/python/csrc/rnnt_beam_search.cc
  sherpa/python/sherpa/__init__.py
  sherpa/python/sherpa/decode.py
  sherpa/python/sherpa/timestamp.py
  sherpa/python/sherpa/utils.py
  sherpa/python/test/CMakeLists.txt
  sherpa/python/test/test_timestamp.py
  sherpa/python/test/test_utils.py
Labels: ready, cpp

#147 Refactor rnnt model for streaming c++ api
  sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
  sherpa/csrc/rnnt_conformer_model.cc
  sherpa/csrc/rnnt_conformer_model.h
  sherpa/csrc/rnnt_conv_emformer_model.cc
  sherpa/csrc/rnnt_conv_emformer_model.h
  sherpa/csrc/rnnt_lstm_model.cc
  sherpa/csrc/rnnt_lstm_model.h
  sherpa/csrc/rnnt_model.h
  sherpa/python/csrc/rnnt_conformer_model.cc
  sherpa/python/csrc/rnnt_conv_emformer_model.cc
  sherpa/python/csrc/rnnt_lstm_model.cc
Labels: ready

#152 Support SSL
  .github/workflows/python_style_check.yml
  .github/workflows/style_check.yml
  docs/source/python/streaming_asr/images/secure-connections/1.png
  docs/source/python/streaming_asr/images/secure-connections/2.png
  docs/source/python/streaming_asr/images/secure-connections/3.png
  docs/source/python/streaming_asr/index.rst
  docs/source/python/streaming_asr/secure-connections.rst
  sherpa/bin/conv_emformer_transducer_stateless2/streaming_server.py
  sherpa/bin/lstm_transducer_stateless/streaming_server.py
  sherpa/bin/pruned_stateless_emformer_rnnt2/streaming_server.py
  sherpa/bin/pruned_transducer_statelessX/offline_client.py
  sherpa/bin/pruned_transducer_statelessX/offline_server.py
  sherpa/bin/streaming_pruned_transducer_statelessX/streaming_server.py
  sherpa/bin/web/.gitignore
  sherpa/bin/web/generate-certificate.py
  sherpa/bin/web/js/offline_record.js
  sherpa/bin/web/js/streaming_record.js
  sherpa/bin/web/js/upload.js
  sherpa/bin/web/offline_record.html
  sherpa/bin/web/start-https-server.py
  sherpa/bin/web/streaming_record.html
  sherpa/bin/web/upload.html
Labels: ready

#155 Limit the number of feature frames to keep for streaming ASR.
  sherpa/bin/conv_emformer_transducer_stateless2/stream.py
  sherpa/bin/lstm_transducer_stateless/stream.py
  sherpa/bin/pruned_stateless_emformer_rnnt2/stream.py
  sherpa/bin/streaming_pruned_transducer_statelessX/stream.py
Labels: ready

#159 fix num_trailing_blanks not update in modified_beam_search
  sherpa/csrc/endpoint.h
  sherpa/csrc/online_asr.cc
  sherpa/csrc/online_stream.cc
Labels: ready, cpp

#165 Add CI for websocket.
  .github/workflows/run-cpp-websocket-test.yaml
  cmake/websocketpp.cmake
  sherpa/bin/pruned_transducer_statelessX/decode_manifest.py
  sherpa/cpp_api/websocket/offline_websocket_client.cc
  sherpa/cpp_api/websocket/offline_websocket_server.cc
  sherpa/cpp_api/websocket/offline_websocket_server_impl.cc
  sherpa/cpp_api/websocket/offline_websocket_server_impl.h
  sherpa/csrc/offline_asr.h
Labels: websocket

#166 Compute RTF of websocket in GitHub actions
  .github/scripts/test-websocket-rtf-wer.sh
  .github/workflows/test-websocket-rtf-wer.yaml
Labels: rtf

#171 Support streaming LSTM
  .github/scripts/run-cpp-test.sh
  .github/workflows/run-cpp-test.yaml
  sherpa/cpp_api/online_recognizer.cc
  sherpa/cpp_api/online_recognizer.h
  sherpa/cpp_api/test_online_recognizer.cc
  sherpa/csrc/online_asr.cc
  sherpa/csrc/online_asr.h
  sherpa/csrc/rnnt_conv_emformer_model.cc
  sherpa/csrc/rnnt_conv_emformer_model.h
  sherpa/csrc/rnnt_lstm_model.cc
  sherpa/csrc/rnnt_lstm_model.h
  sherpa/csrc/rnnt_model.h
  sherpa/csrc/sherpa_online.cc
  sherpa/python/csrc/rnnt_lstm_model.cc
Labels: cpp

#174 Refactor websocket RTF test.
  .github/scripts/test-websocket-rtf-wer.sh
  .github/workflows/test-websocket-rtf-wer.yaml
  sherpa/cpp_api/websocket/online_websocket_server_impl.cc
Labels: rtf
